import assert from 'node:assert/strict';
import test from 'node:test';
import { createCampaignDefinition, validateCampaignDefinition } from './campaign-data.js';
import { applyEnemyIntent, areDistrictsAdjacent, areRegionsConnected, canAttack, clearTemporaryEnemyPressure, createCampaignState, createEnemyIntent, endPlayerRound, nextRandom, reconcileOfflineCampaign, refreshSupply, resolveEnemyRound, restoreCampaign, serializeCampaign, setDistrictStatus, unlockLocalProgress } from './campaign-core.js';

test('definition has ten regions, fifty districts and valid symmetric graph',()=>{const d=createCampaignDefinition();assert.equal(Object.keys(d.regions).length,10);assert.equal(Object.keys(d.districts).length,50);assert.deepEqual(validateCampaignDefinition(d),[]);assert.equal(areDistrictsAdjacent(createCampaignState(1),'garden:dock','garden:learning'),true);assert.equal(areRegionsConnected(createCampaignState(1),'garden','library'),true);assert.equal(areRegionsConnected(createCampaignState(1),'garden','crown-castle'),false);});

test('local progression unlocks in order without skipping boss gate',()=>{let s=createCampaignState();s=setDistrictStatus(s,'garden:dock','controlled','player');s=unlockLocalProgress(s,'garden');assert.equal(s.districts['garden:learning'].status,'neutral');assert.equal(s.districts['garden:village'].status,'locked');s=setDistrictStatus(s,'garden:learning','controlled','player');s=unlockLocalProgress(s,'garden');assert.equal(s.districts['garden:village'].status,'neutral');});

test('attack requires player ownership and explicit adjacency',()=>{let s=createCampaignState();s=setDistrictStatus(s,'garden:dock','controlled','player');s=setDistrictStatus(s,'garden:learning','neutral');assert.equal(canAttack(s,'garden:dock','garden:learning'),true);assert.equal(canAttack(s,'garden:dock','garden:arena'),false);});

test('supply is deterministic and mastery survives contest',()=>{let s=createCampaignState();s=setDistrictStatus(s,'garden:dock','controlled','player');s=setDistrictStatus(s,'garden:learning','mastered','player');s=refreshSupply(s);assert.equal(s.districts['garden:dock'].supply,3);s=applyEnemyIntent(s,{enemyId:'niko',type:'contest',targetId:'garden:learning',telegraphed:true});assert.equal(s.districts['garden:learning'].status,'contested');assert.equal(s.districts['garden:learning'].owner,'player');});

test('raid creates temporary visible supply pressure without rewriting language truth',()=>{let s=createCampaignState();s=setDistrictStatus(s,'garden:dock','controlled','player');s=setDistrictStatus(s,'garden:learning','controlled','player');s=refreshSupply(s);assert.equal(s.districts['garden:dock'].supply,3);s=applyEnemyIntent(s,{enemyId:'riven',type:'raid',targetId:'garden:dock',regionId:'garden',telegraphed:true});assert.equal(s.supplyPressure.garden,1);assert.equal(s.districts['garden:dock'].supply,2);assert.equal(JSON.stringify(s).includes('correctAnswer'),false);s=clearTemporaryEnemyPressure(s,'garden');assert.equal(s.districts['garden:dock'].supply,3);});

test('fortify and blockade are explicit defense state, not hidden extra actions',()=>{let s=createCampaignState();s=setDistrictStatus(s,'garden:learning','controlled','enemy');s=applyEnemyIntent(s,{enemyId:'mako',type:'fortify',targetId:'garden:learning',regionId:'garden',telegraphed:true});assert.equal(s.districts['garden:learning'].fortification,1);s=setDistrictStatus(s,'garden:dock','controlled','player');s=applyEnemyIntent(s,{enemyId:'koda',type:'blockade',targetId:'garden:dock',regionId:'garden',telegraphed:true});assert.equal(s.blockades.length,1);assert.equal(s.blockades[0].enemyId,'koda');assert.equal(s.eventLog.at(-1).telegraphed,true);});

test('seeded rng and enemy intent are reproducible',()=>{const a=createCampaignState(4242),b=createCampaignState(4242);assert.deepEqual(nextRandom(a),nextRandom(b));assert.deepEqual(createEnemyIntent(a),createEnemyIntent(b));});

test('enemy turn is explicit, can plan multiple AIs, and advances only when resolved',()=>{let s=createCampaignState(9);s=setDistrictStatus(s,'garden:dock','controlled','player');s=setDistrictStatus(s,'garden:learning','controlled','enemy');s=endPlayerRound(s,{enemyIds:['niko','mako','riven']});assert.equal(s.phase,'enemy');assert.equal(s.round,1);assert.ok(s.enemyIntents.length<=3);assert.equal(s.enemyDecisionLog.length,3);assert.ok(s.enemyIntents.every(intent=>intent.telegraphed===true));const before=structuredClone(s);const offline=reconcileOfflineCampaign(s);assert.deepEqual(offline,before);assert.equal(offline.round,1);s=resolveEnemyRound(s);assert.equal(s.phase,'player');assert.equal(s.round,2);assert.equal(s.commandPearls,3);});

test('save roundtrip preserves deterministic AI, pressure and blockades',()=>{let s=createCampaignState(123);s=setDistrictStatus(s,'garden:dock','controlled','player');s=applyEnemyIntent(s,{enemyId:'riven',type:'raid',targetId:'garden:dock',regionId:'garden',telegraphed:true});s=applyEnemyIntent(s,{enemyId:'koda',type:'blockade',targetId:'garden:dock',regionId:'garden',telegraphed:true});s=endPlayerRound(s,{enemyIds:['lio']});const restored=restoreCampaign(serializeCampaign(s));assert.deepEqual(restored,s);assert.deepEqual(createEnemyIntent(restored,'lio'),createEnemyIntent(s,'lio'));});

test('legacy campaign saves restore with safe Branch 8 defaults',()=>{const legacy=createCampaignState(5);delete legacy.enemyDecisionLog;delete legacy.supplyPressure;delete legacy.blockades;legacy.version=1;const restored=restoreCampaign(JSON.stringify(legacy));assert.equal(restored.version,2);assert.deepEqual(restored.enemyDecisionLog,[]);assert.deepEqual(restored.supplyPressure,{});assert.deepEqual(restored.blockades,[]);});
